server:
  port: ${SEVER_PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/springboot_k8s}
    username: ${MYSQL_USERNAME:students}
    password: ${MYSQL_PASSWORD:admin_students}
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

    database-platform: org.hibernate.dialect.MySQLDialect